### PR TITLE
issue248:

### PR DESCRIPTION
**Pull request by jknnr**
https://github.com/teamforus/me/issues/248
Voucher model: added expireDate field
Without UI changes

### CODE REVIEW

**Comment by maxvisser** [comment]
just to check below the QR-code we should always display the expire_at from voucher (never the expire date of the product)

**Comment by maxvisser** [comment]
also we should check if its the right date in the right context as the text could say:
use this voucher until 1st of January
or
use this voucher before 1st of January 


Both look the same but could be confusing for the user ( is my voucher still valid on the 1st of januari)

**Comment by jknnr** [comment]
@maxvisser the thing with this issue is that it should go through design department first, we can't really add another string, cause it will not be visible on most devices, so currently the field 'expiration date' is implemented, but not visible. the missing word 'voucher' is added to the dutch localisation

**Comment by maxvisser** [comment]
could you make a screenshot on how it looks on small screen?

**Comment by jknnr** [comment]
@maxvisser  and it's not scrollable IMG_2882

**Comment by maxvisser** [comment]
Thanks I see what you mean :)

**Pull request merged**
