### PR TITLE
Created new dialog and updated required code changes

### PR DESCRIPTION
**Pull request by maestrovsmaster**

### CODE REVIEW

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
❌  provider can add extra amount and  approved 

https://github.com/user-attachments/assets/dc627da9-2fe1-4208-9d0e-bc29e6ae8642

**Dutch version**
❌  translations for buttons:

photo_2024-11-18 15 29 20

❌ input  extra amount

https://github.com/user-attachments/assets/495734ff-ffa9-4ac7-8bc4-e3724fca1b11

❌ input   validation
❌ error message 

https://github.com/user-attachments/assets/79a29414-9787-473a-acdb-b7c1d898be7f

❌ title for input field 

**English version**

Translations:
❌ Title of the sheet should be "Attention"
❌ More information 
❌ Button to decline the request should be "Decline"

**Comment by maestrovsmaster** [comment]
@lexlog  Should the parameter amount_extra_cash always be included in the body of the request, or only when there is a non-zero extra amount?

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
Fixed:
 - provider can add amount and approved
 - provider can add extra amount and approved
 - translation for text:
 -  translations for buttons(partially)
 - Title of the sheet should be "Attention"
 - More information
-  Button to decline the request should be "Decline"

❌ There is a title for the input field in English: "Enter the amount that needs to be paid extra"
and Dutch :"Typ het bij te betalen bedrag"

The placeholder of the field moves up and becomes a title after clicking on the input field.

https://github.com/user-attachments/assets/b42635ad-36e9-4c78-b844-f4bdb411ff0f

❌ error message text is alight  with design
Screenshot_20241120-112652_Me~2

**Dutch version**
❌ Button submit should have translation in Dutch: "Verzenden"

**English version**


--------------------------
 
 **Not related to this PR**

**Review by irinaBerendeeva87 — CHANGES_REQUESTED** [review]
### Checked:
**Fixed:**
-  title for the input field (English and Dutch)
- placeholder

Not fixed:
❌  provider can see information about extra amount  and status in created transaction  after submitted a payment 
like in figma 
Screenshot 2024-11-21 at 10 48 52


❌ Button submit should have translation in Dutch: "Verzenden"

**Review by irinaBerendeeva87 — APPROVED** [review]
### Checked:
✅ Fixed:
- provider can see information about extra amount and status in created transaction after submitted a payment
-  Button submit

**Pull request merged**
