### PR TITLE
fix expired voucher text

### PR DESCRIPTION
**Pull request by jknnr**

### CODE REVIEW

**Comment by maxvisser** [comment]
On this popup modal it should stay the old text..
 image

**Comment by maxvisser** [comment]
Hmm I see the commit which should fix this but it still in an issue if I built it

**Comment by maxvisser** [comment]
@maestrovsmaster could you check it and make a screenshot of the fix?

**Comment by maestrovsmaster** [comment]
device-2020-08-05-123709

**Pull request merged**
