### PR TITLE
Issue524 + update action checkout UI

### PR DESCRIPTION
**Pull request by jknnr**

### CODE REVIEW

**Comment by maxvisser** [comment]
List of actions should show price_locale

**Comment by maxvisser** [comment]
List of actions should show price_locale
image

**Comment by maxvisser** [comment]
Textual changes:

Prijsafspraak should be -> Transactie details
image

'Laat de klant het bedrag aan de kassa betalen' can be removed.
image

**Comment by maxvisser** [comment]
Its to easy to make multiple transactions; will sent you a video

**Comment by maxvisser** [comment]
Currently selecting a provider is switched around
image

**Comment by maxvisser** [comment]
typing in a note which has multiple lines results in that the user can only see one line of the text.

**Comment by jamalv** [comment]
> typing in a note which has multiple lines results in that the user can only see one line of the text.

just discussed with @GerbenBosschieter, and also with @jknnr this is intended behaviour :) - people only make very short notes anyway - and it's still possible to make a longer note

**Comment by maxvisser** [comment]
Prices on the confimation modal are wrong; probably price_locale does not contain the amount which the user has to pay.
image


image
if price for customer is free; no confirmation dialog is needed

**Comment by maxvisser** [comment]
- [ ] if price for customer is free; no confirmation dialog is needed

**Comment by maxvisser** [comment]
- [ ] we still show €0,- on transaction overview; we should hide this value

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 09 02

- If the scenario has a discount with %. Pleas display the value as 20% instead of 20.00%
- In this scenario the the sponsor will do a subsidy of € 5,-. Would be nice to show this like the scenario where the is a discount with €. If if there is no subsidy then don't display it

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 12 51

- Use smaller font size for smaller screens. It doesn't fit

**Comment by GerbenBosschieter** [comment]
Screenshot 2021-01-10 at 12 14 59

- The succes icon overwrites the text on smaller devices.

**Pull request merged**
