### PR TITLE
Issue524 meapp checkout

### PR DESCRIPTION
**Pull request by jknnr**

### CODE REVIEW

**Comment by maxvisser** [comment]
image

1. Price agreement should be in dutch localization "Prijsafspraak"
2. This should be the sponsor organization name; currently it an identity_address

**Comment by maxvisser** [comment]
image
Should be the same amount

**Comment by maxvisser** [comment]
Textarea is missing labels and placeholder text:
image

<details>
<summary>current state<summary>

image

</details>

**Comment by maxvisser** [comment]
image

First sentence is missing dutch localization; Customer pays should be:
Klant betaalt

**Comment by maxvisser** [comment]
Product with no_price and no_price_type free shows €0 euro while it can display 'Free' / 'Gratis'
image

**Review by maxvisser — CHANGES_REQUESTED** [review]
See comments above

**Comment by jamalv** [comment]
Currently in production: https://github.com/teamforus/general/issues/696

**Comment by maartenfv** [comment]
image


What does this mean? Should it be "Resterend bedrag te betalen door klant"?

**Comment by jknnr** [comment]
all comments are fixed except for last one by @maartenfv

**Pull request merged**
